# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
            - name: dudeofawesome/npm-install
  
  # You may pin to the exact commit or the version.
  # uses: dudeofawesome/npm-install@5757b893f4f003f1651a92572c291e4add9fd8f9
  uses: dudeofawesome/npm-install@v1.0.0
  with:
    # Path of dir with package.json.
    package-dir-path: # default is .
    # Path of node_modules dir.
    modules-dir: # optional
    # The cache key.
    cache-key: # optional
                - name: build-npm-action
  # You may pin to the exact commit or the version.
  # uses: ankitasen-ubmainz/build-npm-action@933de398871bd9906e82336d74c730ae222d6fbe
  uses: ankitasen-ubmainz/build-npm-action@v0.2
          
          
